import { TFilterSelect, TLocation } from "../models/ui";

export const estateList: TFilterSelect[] = [
  { id: 1, key: "new_build", value: "Yeni tikili" },
  { id: 2, key: "old_build", value: "Köhnə tikili" },
  { id: 3, key: "coutyard_garden", value: "Həyət evi/Bağ" },
  { id: 4, key: "villa", value: "Villa" },
  { id: 5, key: "office", value: "Ofis" },
  { id: 6, key: "object", value: "Obyekt" },
  { id: 7, key: "garage", value: "Qaraj" },
  { id: 8, key: "land", value: "Torpaq" },
];

export const announceTypes: TFilterSelect[] = [
  { id: 1, key: "alqi-satqi", value: "Alqı - Satqı" },
  { id: 2, key: "kiraye", value: "Kirayə" },
];

export const estateDocument: TLocation[] = [
  { parentKey: "new_build", id: 1, key: "kupcha", value: "Kupça (Çıxarış)" },
  {
    parentKey: "new_build",
    id: 2,
    key: "power_of_attorney",
    value: "Etibarnamə",
  },
  { parentKey: "new_build", id: 3, key: "contract", value: "Müqavilə" },
  {
    parentKey: "new_build",
    id: 4,
    key: "municipal_document",
    value: "Bələdiyyə sənədi",
  },
  { parentKey: "new_build", id: 5, key: "order", value: "Sərəncam" },
  { parentKey: "old_build", id: 6, key: "kupcha", value: "Kupça (Çıxarış)" },
  {
    parentKey: "old_build",
    id: 7,
    key: "power_of_attorney",
    value: "Etibarnamə",
  },
  { parentKey: "old_build", id: 8, key: "contract", value: "Müqavilə" },
  {
    parentKey: "old_build",
    id: 9,
    key: "municipal_document",
    value: "Bələdiyyə sənədi",
  },
  { parentKey: "old_build", id: 10, key: "order", value: "Sərəncam" },
];

export const oldEstateProjectTypes: TLocation[] = [
  { parentKey: "old_build", id: 1, key: "xrusovka", value: "Xruşovka" },
  { parentKey: "old_build", id: 2, key: "stalinka", value: "Stalinka" },
  { parentKey: "old_build", id: 3, key: "contract", value: "Kiyev" },
  { parentKey: "old_build", id: 5, key: "leningrad", value: "Leninqrad" },
  { parentKey: "old_build", id: 5, key: "minsk", value: "Minsk" },
  { parentKey: "old_build", id: 5, key: "italyanka", value: "İtalyanka" },
  { parentKey: "old_build", id: 5, key: "fransiz", value: "Fransız" },
  { parentKey: "old_build", id: 5, key: "experimental", value: "Experimental" },
  { parentKey: "old_build", id: 5, key: "arxitektur", value: "Arxitektur" },
];

export const sellTypes: TLocation[] = [
  { parentKey: "new_build", id: 1, key: "credit", value: "Kredit" },
  { parentKey: "new_build", id: 2, key: "cash", value: "Nağd" },
  {
    parentKey: "new_build",
    id: 3,
    key: "non_percent_credit",
    value: "Faizsiz kredit",
  },
  { parentKey: "new_build", id: 4, key: "mortgage", value: "İpoteka" },
  { parentKey: "new_build", id: 5, key: "barter", value: "Barter" },
];

export const distirctList: TFilterSelect[] = [
  { id: 1, key: "any", value: "İstənilən şəhər" },
  { id: 2, key: "bakı", value: "Bakı" },
  { id: 3, key: "agcabedi", value: "Ağcabədi" },
  { id: 4, key: "agdam", value: "Ağdam" },
  { id: 5, key: "agdas", value: "Ağdaş" },
  { id: 6, key: "agstafa", value: "Ağstafa" },
  { id: 7, key: "agsu", value: "Ağsu" },
  { id: 8, key: "astara", value: "Astara" },
  { id: 9, key: "balakan", value: "Balakən" },
  { id: 10, key: "beyleqan", value: "Beyləqan" },
  { id: 11, key: "berde", value: "Bərdə" },
  { id: 12, key: "bilesuvar", value: "Biləsuvar" },
  { id: 13, key: "celilabad", value: "Cəlilabad" },
  { id: 14, key: "daskesen", value: "Daşkəsən" },
  { id: 15, key: "gedebey", value: "Gədəbəy" },
  { id: 16, key: "gence", value: "Gəncə" },
  { id: 17, key: "goranboy", value: "Goranboy" },
  { id: 18, key: "goycay", value: "Göyçay" },
  { id: 19, key: "goygol", value: "Göygöl" },
  { id: 20, key: "haciqabul", value: "Hacıqabul" },
  { id: 21, key: "xacmaz", value: "Xaçmaz" },
  { id: 22, key: "xirdalan", value: "Xırdalan" },
  { id: 23, key: "xizi", value: "Xızı" },
  { id: 24, key: "xudat", value: "Xudat" },
  { id: 25, key: "imisli", value: "İmişli" },
  { id: 26, key: "ismayilli", value: "İsmayıllı" },
  { id: 27, key: "kurdermir", value: "Kürdəmir" },
  { id: 28, key: "qax", value: "Qax" },
  { id: 29, key: "qazax", value: "Qazax" },
  { id: 30, key: "qebele", value: "Qəbələ" },
  { id: 31, key: "qobustan", value: "Qobustan" },
  { id: 32, key: "quba", value: "Quba" },
  { id: 33, key: "qusar", value: "Qusar" },
  { id: 34, key: "lerik", value: "Lerik" },
  { id: 35, key: "lenkeran", value: "Lənkəran" },
  { id: 36, key: "masalli", value: "Masallı" },
  { id: 37, key: "mingecevir", value: "Mingəçevir" },
  { id: 38, key: "naftalan", value: "Naftalan" },
  { id: 39, key: "naxcivan", value: "Naxçıvan" },
  { id: 40, key: "naxcivan_mr", value: "Naxçıvan MR" },
  { id: 41, key: "neftcala", value: "Neftçala" },
  { id: 42, key: "zerdab", value: "Zərdab" },
  { id: 43, key: "oguz", value: "Oğuz" },
  { id: 44, key: "saatli", value: "Saatlı" },
  { id: 45, key: "sabirabad", value: "Sabirabad" },
  { id: 46, key: "salyan", value: "Salyan" },
  { id: 47, key: "samux", value: "Samux" },
  { id: 48, key: "siyezen", value: "Siyəzən" },
  { id: 49, key: "sumqayiq", value: "Sumqayıt" },
  { id: 50, key: "sabnran", value: "Şabran" },
  { id: 51, key: "samaxi", value: "Şamaxı" },
  { id: 52, key: "seki", value: "Şəki" },
  { id: 53, key: "semkir", value: "Şəmkir" },
  { id: 54, key: "sirvan", value: "Şirvan" },
  { id: 55, key: "terter", value: "Tərtər" },
  { id: 56, key: "tovuz", value: "Tovuz" },
  { id: 57, key: "ucar", value: "Ucar" },
  { id: 58, key: "yardımlı", value: "Yardımlı" },
  { id: 59, key: "yevlax", value: "Yevlax" },
  { id: 60, key: "zaqatala", value: "Zaqatala" },
];

export const underGroundList: TLocation[] = [
  { parentKey: "bakı", id: 1, key: "iceriseher", value: "İçərişəhər" },
  { parentKey: "bakı", id: 2, key: "sahil", value: "Sahil" },
  { parentKey: "bakı", id: 3, key: "28_may", value: "28 May" },
  { parentKey: "bakı", id: 4, key: "genclik", value: "Gənclik" },
  {
    parentKey: "bakı",
    id: 5,
    key: "nariman_narimanov",
    value: "Nəriman Nərimanov",
  },
  { parentKey: "bakı", id: 6, key: "bakmil", value: "Bakmil" },
  { parentKey: "bakı", id: 7, key: "ulduz", value: "Ulduz" },
  { parentKey: "bakı", id: 8, key: "koroglu", value: "Koroğlu" },
  { parentKey: "bakı", id: 9, key: "qara_qarayev", value: "Qara Qarayev" },
  { parentKey: "bakı", id: 10, key: "neftciler", value: "Neftçilər" },
  { parentKey: "bakı", id: 11, key: "xalqlar", value: "Xalqlar Dostluğu" },
  { parentKey: "bakı", id: 12, key: "ahmadli", value: "Əhmədli" },
  { parentKey: "bakı", id: 13, key: "hazi_aslanov", value: "Həzi Aslanov" },
  { parentKey: "bakı", id: 14, key: "nizami", value: "Nizami" },
  {
    parentKey: "bakı",
    id: 15,
    key: "elmler_akademiyasi",
    value: "Elmlər Akademiyası",
  },
  { parentKey: "bakı", id: 16, key: "insaatcilar", value: "İnşaatçılar" },
  { parentKey: "bakı", id: 17, key: "20_yanvar", value: "20 Yanvar" },
  { parentKey: "bakı", id: 18, key: "memar_acami", value: "Memar Əcəmi" },
  { parentKey: "bakı", id: 19, key: "nesimi", value: "Nəsimi" },
  { parentKey: "bakı", id: 20, key: "azadliq", value: "Azadlıq" },
  { parentKey: "bakı", id: 21, key: "dernegul", value: "Dərnəgül" },
  { parentKey: "bakı", id: 22, key: "xatai", value: "Şah İsmayıl Xətai" },
  { parentKey: "bakı", id: 23, key: "cefer_cabbarli", value: "Cəfər Cabbarlı" },
  { parentKey: "bakı", id: 24, key: "avtovagzal", value: "Avtovağzal" },
  { parentKey: "bakı", id: 25, key: "memar_acami_2", value: "Memar Əcəmi-2" },
  { parentKey: "bakı", id: 26, key: "8_noyabr", value: "8 Noyabr" },
  { parentKey: "bakı", id: 27, key: "xocasen", value: "Xocəsən" },
];

export const undergroundAroundList: TLocation[] = [
  { parentKey: "insaatcilar", id: 1, key: "kfc", value: "Kfc" },
  { parentKey: "insaatcilar", id: 2, key: "ag_ciceyim", value: "Ağ Çiçəyim" },
  {
    parentKey: "insaatcilar",
    id: 3,
    key: "gunes_petrol",
    value: "Günəş Petrol",
  },
  {
    parentKey: "insaatcilar",
    id: 4,
    key: "yeni_yasamal_bravo",
    value: "Yeni Yasamal Bravo",
  },
  { parentKey: "insaatcilar", id: 5, key: "saf_su", value: "Saf Su" },
  {
    parentKey: "insaatcilar",
    id: 6,
    key: "am_sherifzade",
    value: "A.M Şərifzadə küçəsi",
  },
  {
    parentKey: "elmler_akademiyasi",
    id: 7,
    key: "bdu",
    value: "Bakı Dövlət Universiteti",
  },
  {
    parentKey: "elmler_akademiyasi",
    id: 8,
    key: "aztu",
    value: "Azərbaycan Texniki Universiteti",
  },
  {
    parentKey: "elmler_akademiyasi",
    id: 9,
    key: "azmiu",
    value: "Azərbaycan Memarlıq və İnşaat Universiteti",
  },
  {
    parentKey: "elmler_akademiyasi",
    id: 10,
    key: "hc_park",
    value: "Hüseyn Cavid parkı",
  },
  {
    parentKey: "elmler_akademiyasi",
    id: 11,
    key: "mother_care",
    value: "Mother Care",
  },
  {
    parentKey: "elmler_akademiyasi",
    id: 12,
    key: "xalq_bank",
    value: "Xalq Bank",
  },
  {
    parentKey: "elmler_akademiyasi",
    id: 13,
    key: "gormuk_komitesi",
    value: "Gömrük Komitəsi",
  },
  { parentKey: "nizami", id: 14, key: "caspian_plaza", value: "Caspian Plaza" },
  { parentKey: "nizami", id: 15, key: "nizami_mall", value: "Nizami Mall" },
  { parentKey: "20_yanvar", id: 16, key: "ictimai_tv", value: "Ictimai Tv" },
];

export const distirctTownshipList: TLocation[] = [
  { parentKey: "bakı", id: 1, key: "abseron", value: "Abşeron" },
  { parentKey: "bakı", id: 1, key: "xetai", value: "Xətai" },
  { parentKey: "bakı", id: 1, key: "nerimanov", value: "Nərimanov" },
  { parentKey: "bakı", id: 1, key: "sebail", value: "Səbail" },
  { parentKey: "bakı", id: 1, key: "nesimi", value: "Nəsimi" },
  { parentKey: "bakı", id: 1, key: "xezer", value: "Xəzər" },
  { parentKey: "bakı", id: 1, key: "suraxani", value: "Suraxanı" },
  { parentKey: "bakı", id: 1, key: "nizami", value: "Nizami" },
  { parentKey: "bakı", id: 1, key: "pirallahi", value: "Pirallahı" },
  { parentKey: "bakı", id: 1, key: "qaradag", value: "Qaradağ" },
  { parentKey: "bakı", id: 1, key: "sabuncu", value: "Sabunçu" },
  { parentKey: "bakı", id: 1, key: "yasamal", value: "Yasamal" },
];

export const townShipAround: TLocation[] = [
  { parentKey: "abseron", id: 1, key: "asagi_guzde", value: "Aşağı Güzdə" },
  { parentKey: "abseron", id: 2, key: "ceyranbatan", value: "Ceyranbatan" },
  { parentKey: "abseron", id: 3, key: "cicek", value: "Çiçək" },
  { parentKey: "abseron", id: 4, key: "digah", value: "Digah" },
  { parentKey: "abseron", id: 5, key: "fatmayı", value: "Fatmayı" },
  { parentKey: "abseron", id: 6, key: "goredil", value: "Görədil" },
  { parentKey: "abseron", id: 7, key: "hokmeli", value: "Hökməli" },
  { parentKey: "abseron", id: 8, key: "kohne_corat", value: "Köhnə Corat" },
  { parentKey: "abseron", id: 9, key: "qobu", value: "Qobu" },
  { parentKey: "abseron", id: 10, key: "masazır", value: "Masazır" },
  { parentKey: "abseron", id: 11, key: "mehdiabad", value: "Mehdiabad" },
  { parentKey: "abseron", id: 12, key: "memmedli", value: "Məmmədli" },
  { parentKey: "abseron", id: 13, key: "novxani", value: "Novxanı" },
  { parentKey: "abseron", id: 14, key: "pirekeskul", value: "Pirəkəşkül" },
  { parentKey: "abseron", id: 15, key: "saray", value: "Saray" },
  { parentKey: "abseron", id: 16, key: "yeni_corat", value: "Yeni Corat" },
  { parentKey: "abseron", id: 17, key: "zugulba", value: "Zuğulba" },
  { parentKey: "xetai", id: 18, key: "ag_seher", value: "Ağ şəhər" },
  { parentKey: "xetai", id: 19, key: "ehmedli", value: "Əhmədli" },
  { parentKey: "xetai", id: 20, key: "hezi_aslanov", value: "Həzi Aslanov" },
  { parentKey: "xetai", id: 21, key: "kohne_gunesli", value: "Köhnə Günəşli" },
  { parentKey: "xetai", id: 22, key: "nzs", value: "NZS" },
  { parentKey: "nerimanov", id: 23, key: "boyuksor", value: "Böyükşor" },
  { parentKey: "sebail", id: 24, key: "20_ci_sahe", value: "20-ci sahə" },
  { parentKey: "sebail", id: 25, key: "badamdar", value: "Badamdar" },
  { parentKey: "sebail", id: 26, key: "bayil", value: "Bayıl" },
  { parentKey: "sebail", id: 27, key: "bibi_heybet", value: "Bibi Heybət" },
  { parentKey: "sebail", id: 28, key: "sixov", value: "Şıxov" },
  {
    parentKey: "nesimi",
    id: 29,
    key: "1_ci_mikrorayon",
    value: "1-ci mikrorayon",
  },
  {
    parentKey: "nesimi",
    id: 30,
    key: "2_ci_mikrorayon",
    value: "2-ci mikrorayon",
  },
  {
    parentKey: "nesimi",
    id: 31,
    key: "3_cu_mikrorayon",
    value: "3-cü mikrorayon",
  },
  {
    parentKey: "nesimi",
    id: 32,
    key: "4-cü mikrorayon",
    value: "4_cu_mikrorayon",
  },
  {
    parentKey: "nesimi",
    id: 33,
    key: "5-ci mikrorayon",
    value: "5_ci_mikrorayon",
  },
  { parentKey: "nesimi", id: 34, key: "kubinka", value: "Kubinka" },
  { parentKey: "xezer", id: 35, key: "bine", value: "Binə" },
  { parentKey: "xezer", id: 36, key: "buzovna", value: "Buzovna" },
  { parentKey: "xezer", id: 37, key: "dubendi", value: "Dübəndi" },
  { parentKey: "xezer", id: 38, key: "gurgen", value: "Gürgən" },
  { parentKey: "xezer", id: 39, key: "qala", value: "Qala" },
  { parentKey: "xezer", id: 40, key: "merdekan", value: "Mərdəkan" },
  { parentKey: "xezer", id: 41, key: "sagan", value: "Şağan" },
  { parentKey: "xezer", id: 42, key: "simal_dres", value: "Şimal DRES" },
  { parentKey: "xezer", id: 43, key: "suvelan", value: "Şüvəlan" },
  { parentKey: "xezer", id: 44, key: "turkan", value: "Türkan" },
  { parentKey: "xezer", id: 45, key: "zire", value: "Zirə" },
  { parentKey: "suraxani", id: 46, key: "bahar", value: "Bahar" },
  { parentKey: "suraxani", id: 47, key: "bulbule", value: "Bülbülə" },
  { parentKey: "suraxani", id: 48, key: "deDE_QORQUD", value: "Dədə Qorqud" },
  { parentKey: "suraxani", id: 49, key: "emircan", value: "Əmircan" },
  { parentKey: "suraxani", id: 50, key: "gunesli", value: "Günəşli" },
  { parentKey: "suraxani", id: 51, key: "hovsan", value: "Hövsan" },
  { parentKey: "suraxani", id: 52, key: "qaracuxur", value: "Qaraçuxur" },
  { parentKey: "suraxani", id: 53, key: "massiv_a", value: "Massiv A" },
  { parentKey: "suraxani", id: 54, key: "massiv_b", value: "Massiv B" },
  { parentKey: "suraxani", id: 55, key: "massiv_c", value: "Massiv D" },
  { parentKey: "suraxani", id: 56, key: "massiv_g", value: "Massiv G" },
  { parentKey: "suraxani", id: 57, key: "massiv_v", value: "Massiv V" },
  { parentKey: "suraxani", id: 58, key: "suraxanı", value: "Suraxanı" },
  { parentKey: "suraxani", id: 59, key: "serq", value: "Şərq" },
  { parentKey: "suraxani", id: 60, key: "yeni_gunesli", value: "Yeni Günəşli" },
  {
    parentKey: "suraxani",
    id: 61,
    key: "yeni_suraxanı",
    value: "Yeni Suraxanı",
  },
  { parentKey: "suraxani", id: 62, key: "zig", value: "Zığ" },
  { parentKey: "nizami", id: 63, key: "8_ci_kilometr", value: "8-ci kilometr" },
  { parentKey: "nizami", id: 64, key: "kesle", value: "Keşlə" },
  { parentKey: "qaradag", id: 65, key: "elet", value: "Ələt" },
  { parentKey: "qaradag", id: 66, key: "qizildas", value: "Qızıldaş" },
  { parentKey: "qaradag", id: 67, key: "qobustan", value: "Qobustan" },
  { parentKey: "qaradag", id: 68, key: "lokbatan", value: "Lökbatan" },
  { parentKey: "qaradag", id: 69, key: "musfiqabad", value: "Müşfiqabad" },
  { parentKey: "qaradag", id: 70, key: "puta", value: "Puta" },
  { parentKey: "qaradag", id: 71, key: "sahil", value: "Sahil" },
  { parentKey: "qaradag", id: 72, key: "sengecal", value: "Səngəçal" },
  { parentKey: "qaradag", id: 73, key: "subanı", value: "Şubanı" },
  { parentKey: "sabuncu", id: 74, key: "albalılıq", value: "Albalılıq" },
  { parentKey: "sabuncu", id: 75, key: "bakıxanov", value: "Bakıxanov" },
  { parentKey: "sabuncu", id: 76, key: "balaxanı", value: "Balaxanı" },
  { parentKey: "sabuncu", id: 77, key: "bilgeh", value: "Bilgəh" },
  { parentKey: "sabuncu", id: 78, key: "kurdexani", value: "Kürdəxanı" },
  { parentKey: "sabuncu", id: 79, key: "mastaga", value: "Maştağa" },
  { parentKey: "sabuncu", id: 80, key: "nardaran", value: "Nardaran" },
  { parentKey: "sabuncu", id: 81, key: "pirsagi", value: "Pirşağı" },
  { parentKey: "sabuncu", id: 82, key: "ramana", value: "Ramana" },
  { parentKey: "sabuncu", id: 83, key: "sabuncu", value: "Sabunçu" },
  { parentKey: "sabuncu", id: 84, key: "savalan", value: "Savalan" },
  {
    parentKey: "sabuncu",
    id: 85,
    key: "Yeni Balaxanı",
    value: "Yeni Balaxanı",
  },
  { parentKey: "sabuncu", id: 86, key: "yeni_ramana", value: "Yeni Ramana" },
  { parentKey: "sabuncu", id: 87, key: "zabrat", value: "Zabrat" },
  { parentKey: "yasamal", id: 88, key: "yasamal", value: "Yasamal" },
  { parentKey: "yasamal", id: 89, key: "yeni_yasamal", value: "Yeni Yasamal" },
];

export const repairTypes = [
  { id: 1, key: "all", value: "Hamısı" },
  { id: 2, key: "repair", value: "Təmirli" },
  { id: 3, key: "min-repair", value: "Orta Təmirli" },
  { id: 3, key: "non-repair", value: "Təmirsiz" },
];

export const announceImages = [
  "https://api.bahmanahmadli.com/storage/65/11.jpg",
  "https://api.bahmanahmadli.com/storage/48/111.jpg",
  "https://api.bahmanahmadli.com/storage/50/113.jpg",
  "https://api.bahmanahmadli.com/storage/49/112.jpg",
  "https://api.bahmanahmadli.com/storage/66/11.jpg",
  "https://api.bahmanahmadli.com/storage/68/13.jpg",
  "https://api.bahmanahmadli.com/storage/67/12.jpg",
  "https://api.bahmanahmadli.com/storage/136/img-1.jpeg",
  "https://api.bahmanahmadli.com/storage/139/img-3.jpeg",
  "https://api.bahmanahmadli.com/storage/138/img-2.jpeg",
];
